= Java Project using JTable-style syntax but written in Groovy
jnorthr <james.b.northrop@googlemail.com>
v1.0
:icons: font

''''

IMPORTANT: Travis Build Status for Master Branch: [![Build Status](https://travis-ci.com/jnorthr/.svg?branch=master)](https://travis-ci.com/jnorthr/JTables)

''''

A Gradle project for users who develop with Gradle and Groovy/Java. Clone includes gradle build tool wrapper and folder structure like maven/gradle so you don't need an installed gradle build tool.
 
== Pre-requisites

1. Working internet connection
2. Installed Git client to copy/clone this repo
3. Ability to use terminal console
4. Improve README.adoc


== Steps

. Open terminal console
. Change directory into a target folder location
. Run this command to create a folder and copy down all the pieces :

   git clone https://github.com/jnorthr/JTables.git

. **cd JTables /**  for example
. **./gradlew** runs a series of defined tasks to build and test code samples
. After prior step completes, examine your folder to find the **/build/** sub-folder with test results


NOTE: **.travis.yml** needs extra logic to be able to push to github repo and have Travis C/I testing work as expected. It may be missing.


.Terminal Script
====
. cd ~/Dropbox/Projects/
. mkdir FredTest
. cd FredTest/
. git clone https://github.com/jnorthr/JTables.git
. gradlew
====

Examine *FredTest* folder for successful results.
