/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
//import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*
import com.jim.toolkit.gui.DatePicker;

class DatePickerTest extends Specification {
    def "Simple DatePicker constructor returns proper name of class"() {
        setup:
	        DatePicker obj = new DatePicker();
		
        when:
        	def result = obj.classname

        then:
        	result == "DatePicker"
    } // end of method

} // end of class
