/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
//import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*
import com.jim.toolkit.Parser;

class ParserTest extends Specification {
    def "Simple Parser constructor returns proper name of class"() {
        setup:
	        Parser obj = new Parser();
		
        when:
        	def result = obj.load()

        then:
        	result == null
    } // end of method

} // end of class
