/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class CellTest extends Specification {
    def "Simple Cell constructor returns proper name of action"() {
        setup:
		    Date dat = Date.parse('yyy-MM-dd','2017-01-01');
			Cell obj = new Cell([d:dat, type:0, client:0, purpose:'Start',amount:-123.45])
		
        when:
        	def result = obj.cvtType()

        then:
        	result == "Balance"
        	obj.amount == -123.45
        	//obj.d == 'Sun Jan 01 00:00:00 CET 2017'
        	obj.purpose == 'Start'
        	obj.client == 0
    }
}
