/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.Cells;
import com.jim.toolkit.Cell;

class CellsTest extends Specification {

    def "Simple Cells constructor returns proper string for a date"() {
        setup:
		Cells obj = null
		
        when:
		obj = new Cells()
		Date dat =  obj.cvt('2017-09-21');

        then:
        	dat.toString().startsWith("Thu Sep 21") == true
    } // end of test
    
    
    def "Simple Cells constructor then add a Cell using Map"() {
        setup:
		    Date dat = Date.parse('yyy-MM-dd','2017-01-01');
			Cells obj = new Cells();
			Cell c = null;			
	        dat += 4;
    	    Map m = [id:27, date:dat, type:'C', amount:-75.05, number:13, flag:true, reason:'Bingo'];
        	c = new Cell(m);
	        println "Cell(map).toString() = [${c.toString()}]"

        when:
			obj.add(c);

        then:
			obj.cells.size() == 1
			//obj.nextID == 1
    } // end of test
    
    
} // end of class
