/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.gui.ClientDisplay;

class ClientDisplayTest extends Specification {

    def "Simple ClientDisplay constructor returns usable object display"() {
        setup:
		    ClientDisplay obj = null;
            
        when:
            obj = new ClientDisplay();
            obj.say "Hi there"

        then:
        	obj != null;
            obj.setVisible(true);
            obj._resultArea != null;
    } // end of test

    def "Simple ClientDisplay object loader() test"() {
        setup:
            ClientDisplay obj = null;
            
        when:
            obj = new ClientDisplay();
            def ans = obj.loader(3)

        then:
            ans != null;
            obj._resultArea.text.startsWith("   Id   CCY   Usage     N a m e                        Purpose") == true
    } // end of test

} // end class
