/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.tools.ClientSupport

class ClientSupportTest extends Specification {

    def "Simple ClientSupport constructor returns proper string for a date"() {
        setup:
    		ClientSupport obj = null
		
        when:
		  obj = new ClientSupport()
		
        then:
        	obj != null;
    } // end of test
    
    
    def "Simple ClientSupport constructor using Map"() {
        setup:
			ClientSupport obj = new ClientSupport();
	        //println "ClientSupport().toString() = [${obj.toString()}]"

        when:
			String who = obj.getClient(1);

        then:
			who.size() != 1			
    } // end of test
    
} // end of class
