/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.tools.DateMath;
import static java.util.Calendar.*

class DateMathTest extends Specification {
    def "Simple DateMath constructor returns proper name of class"() {
        setup:
	        DateMath obj = new DateMath();
		
        when:
        	def result = obj.classname

        then:
        	result == "DateMath"
    } // end of method

    
    def "Compare Java Date convert value VS DateSupport value for same date"() {
        setup:
		    //Date dat = Date.parse('yyy-MM-dd','2017-01-01');
	        DateMath obj = new DateMath();
			//Date d = new Date();
			
		when:
			def ans = obj.check("2017-12-13");			
		then:
			ans == true;
			//dat[MONTH] == d[MONTH];
			//dat[DATE] == d[DATE];
	} // end of method
	
} // end of class
