/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.tools.DateArithmetic;
import static java.util.Calendar.*

class DateArithmeticTest extends Specification {
    def "Simple DateArithmetic constructor returns proper name of class"() {
        setup:
	        DateArithmetic obj = new DateArithmetic();
		
        when:
        	def result = obj.classname

        then:
        	result == "DateArithmetic"
    } // end of method

    
    def "Increment Java Date value by 7 months from same date"() {
        setup:
		    Date date = Date.parse('yyy-MM-dd','2017-01-01');
	        DateArithmetic obj = new DateArithmetic();
			
		when:
			def dat = obj.bumpMonth(date, 7);
			//println "... DateArithmeticTest:"+dat.toString();
		then:
			dat[YEAR] == 2017;
			dat[MONTH] == 7;
			dat[DATE] == 01
	} // end of method
	
} // end of class
