/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.tools.DateSupport;
import static java.util.Calendar.*
import com.jim.toolkit.tools.DateSupport;

class DateSupportTest extends Specification {
    def "Simple DateSupport constructor returns proper name of action"() {
        setup:
	        DateSupport obj = new DateSupport();
		
        when:
        	def result = obj.classname

        then:
        	result == "DateSupport"
    } // end of method

    
    def "Compare Java Date convert value VS DateSupport value for same date"() {
        setup:
		    Date dat = Date.parse('yyy-MM-dd','2017-01-01');
	        DateSupport obj = new DateSupport();
			Date d = new Date();
			
		when:
			println ""
			if (obj.isIsoDate("2017-01-01"))
			{
				d = obj.getIsoDate();
				println "... DateSupportTest.getIsoDate()="+d;
			}
			
		then:
			dat[YEAR] == d[YEAR];
			dat[MONTH] == d[MONTH];
			dat[DATE] == d[DATE];
	} // end of method
	
} // end of class
