/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.database.H2RowSupport;
import java.sql.SQLException;

class H2RowSupportTest extends Specification {
    def "Simple H2RowSupport constructor returns proper names for database connection values"() {
        setup:
		    H2RowSupport obj = null;
        when:
            obj = new H2RowSupport();
        then:
        	obj.classname == "H2RowSupport"
    } // end of test


    def "obj.toString() from H2RowSupport()"() {
        setup:
            H2RowSupport obj = new H2RowSupport();

        when:
            def selectmsg = obj.toString();

        then:
            selectmsg.startsWith("classname=H2RowSupport\njava.io.File.separator=") == true
    } // end of test


} // end of class
