/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*

class LoaderSupportTest extends Specification {
    def "Simple LoaderSupport constructor returns proper name of class"() {
        setup:
	        LoaderSupport obj = new LoaderSupport();
		
        when:
        	def result = obj.classname

        then:
        	result == "LoaderSupport"
    } // end of method

/*    
    def "Add 7 days to Java Date value"() {
        setup:
		    Date datex = Date.parse('yyy-MM-dd','2017-01-01');
	        Loader obj = new Loader();
			
		when:
			def ans = obj.check("2017-12-13");			
			def ans2 = obj.check(datex.toString());			

		then:
			ans == true;
			ans2 == true;
			//dat[MONTH] == d[MONTH];
			//dat[DATE] == d[DATE];
	} // end of method
*/

} // end of class
