/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*

class LoaderSupportTest extends Specification {
    def "Simple LoaderSupport constructor returns proper name of class"() {
        setup:
	        LoaderSupport obj = new LoaderSupport();
		
        when:
        	def result = obj.classname

        then:
        	result == "LoaderSupport"
    } // end of method


    def "Load text string to create a Cell"() {
        setup:
		    String tx = /  78   2017-01-21 A -1.23 6   true  "'Haircuts Are   Us'"  | 'Mad Max' /;
	        LoaderSupport obj = new LoaderSupport(true);
			
		when:
			def ans = obj.loadReason(tx);			
			println "... LoaderSupportTest.load()="+ans.toString();			

		then:
		    ans.reason == /Haircuts Are   Us/
		    ans.name == /Mad Max/
	} // end of method

} // end of class
