/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
//import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*
import com.jim.toolkit.gui.MrHakiGUI;

class MrHakiGUITest extends Specification {
    def "Simple MrHakiGUI constructor returns proper name of class"() {
        setup:
	        MrHakiGUI obj = new MrHakiGUI();
		
        when:
        	def result = obj.classname

        then:
        	result == "MrHakiGUI"
    } // end of method

} // end of class
