/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
//import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*
import com.jim.toolkit.gui.RadioButtons;

class RadioButtonsTest extends Specification {
    def "Simple RadioButtons constructor returns proper name of class"() {
        setup:
	        RadioButtons obj = new RadioButtons();
		
        when:
        	def result = obj.classname

        then:
        	result == "RadioButtons"
    } // end of method

} // end of class
