/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
//import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*
import com.jim.toolkit.gui.T2;

class T2Test extends Specification {
    def "Simple T2 constructor returns proper name of class"() {
        setup:
	        T2 obj = new T2();
		
        when:
        	def result = obj.classname

        then:
        	result == "T2"
    } // end of method

} // end of class
