/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
import com.jim.toolkit.gui.TestNumberFmts; // com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*

class TestNumberFmtsTest extends Specification {
    def "Simple TestNumberFmts constructor returns proper name of class"() {
        setup:
	        TestNumberFmts obj = new TestNumberFmts();
		
        when:
        	def result = obj.classname

        then:
        	result == "TestNumberFmts"
    } // end of method

} // end of class
