/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification
//import com.jim.toolkit.database.LoaderSupport;
import static java.util.Calendar.*
import com.jim.toolkit.gui.TransactionGUI;

class TransactionGUITest extends Specification {
    def "Simple TransactionGUI constructor returns proper name of class"() {
        setup:
	        TransactionGUI obj = new TransactionGUI();
		
        when:
        	def result = obj.classname

        then:
        	result == "TransactionGUI"
    } // end of method

} // end of class
